# Generated by Django 4.1.2 on 2024-05-09 13:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0007_alter_testimonial_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
    ]
