# Generated by Django 4.1.2 on 2024-04-29 12:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
