# Generated by Django 4.1.2 on 2024-04-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='about',
            field=models.CharField(default='About this blog', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='static/media/blog'),
        ),
    ]
