# Generated by Django 4.1.2 on 2024-05-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_about_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('course_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bundle_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('courses', models.ManyToManyField(to='main.course')),
            ],
        ),
    ]
